In [3]:
with open("Test1_File.txt",'x') as file:
  file.write("Hello World")
  print("New file created")



New file created


In [4]:
with open("Test_File.txt",'r') as file:
  for line in file:
    print(line.strip())


Hello World


In [5]:
with open("Test_File.txt",'a') as file:
  file.write("\nThis is a new line")
  print("Data Appended")

Data Appended


In [6]:
with open("Test_File.txt",'r') as file:
  for line in file:
    print(line.strip())


Hello World
This is a new line


In [7]:
with open("Test_File1.txt","w") as file:
  file.write("This is a new file")
  print("New file created")

New file created


In [8]:
with open("Test_File1.txt","w") as file:
  file.write("overwritten with w command in file")
  print(" content replaced")

 content replaced


In [12]:
with open("Test_File1.txt","a") as file:
  file.write("\nAdding a line at end of line with a command in file")
  print(" content Added")

 content Added


In [13]:
with open("Test_File1.txt","r") as file:
  for line in file:
    print(line.strip())

overwritten with w command in fileAdding a line at end of line with a command in file
Adding a line at end of line with a command in file


In [26]:
with open("Test_File1.txt", "r") as file:
    lines = file.readlines()

# Modify second line (index 1)
if len(lines) > 1:
    lines[1] = "Append at line 2\n"
else:
    lines.append("Append at line 2\n")

with open("Test_File1.txt", "w") as file:
    file.writelines(lines)

In [28]:
with open("Test_File1.txt", "r") as file:
    lines = file.readlines()

lines.insert(2,"Add a line at 2")

with open("Test_File1.txt", "w") as file:
    file.writelines(lines)
print(lines)

['overwritten with w command in fileAdding a line at end of line with a command in file\n', 'Append at line 2\n', 'Add a line at 2', 'Add a line at 2']


In [39]:
with open("counter.txt",'r+') as file:
  current = int(file.read())
  print(f"Previous visitors: {current}")

  count = current + 1
  print(f"New visitors: {count}")

  file.seek(0)
  file.write(str(count))
  print("Counter updated")


Previous visitors: 43
New visitors: 44
Counter updated


In [44]:
with open("Test_File1.txt", "r+") as file:
 content = file.read() # Cursor is now at END of file
 file.seek(0) # cursor is at starting point
 file.write("\n New data")

In [56]:
with open("Test_File1.txt", "w+") as file:
# Write some data
  file.write("Line 1\n")
  file.write("Line 2\n")
  file.write("Line 3\n")
  file.seek(0)
# Read what we just wrote
  content = file.read()
  print(content)

Line 1
Line 2
Line 3



In [59]:
with open("temp_calculation.txt", "w+") as file:
# Write calculations
  file.write("10 + 20 = 30\n")
  file.write("15 * 3 = 5\n")
# Read them back to verify
  file.seek(0)
  for line in file:
      print(f"Verified: {line.strip()}")



Verified: 10 + 20 = 30
Verified: 15 * 3 = 5


In [74]:
import datetime

# Get today's date
today = datetime.date.today()

# Create filename like log_2026-03-26.txt
filename = f"log_{today}.txt"
print(filename)

try:
    # "x" mode → create file ONLY if it doesn't exist
    with open(filename, "x") as file:
        file.write(f"Log started on {today}\n")
        print(f"Created new log: {filename}")

except FileExistsError:
    print(f"Log for {today} already exists!")

    # Append to existing file
    with open(filename, "a") as file:
        file.write("Additional entry\n")

log_2026-03-26.txt
Log for 2026-03-26 already exists!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [76]:
with open("img24.jpg", "rb") as file:
 image_data = file.read()
 print(f"Image size: {len(image_data)} bytes")


Image size: 1150704 bytes


In [82]:
# Copy image from one file to another
with open("img24.jpg", "rb") as source:
  image_data = source.read()
  print(f"Image size: {len(image_data)} bytes")
with open("copy.jpg", "wb") as destination:
  copied_image = destination.write(image_data)
  print(f"Image copied successfully! with {copied_image} bytes")

Image size: 1150704 bytes
Image copied successfully! with 1150704 bytes


In [85]:
import struct

print(struct.calcsize('c'))

1


In [92]:
letters =['A','B']

with open('text.bin',"wb") as file:
  for char in letters:
    print(file.write(struct.pack('c',char.encode())))
with open("text.bin", "ab") as file:
 print(file.write(struct.pack('i',10)))


1
1
4


In [100]:
with open("output2.txt","w") as file:
 file.write("Line1\n")
 file.write("Line2\n")
 file.write("Line3\n")

 lines = ["line4\n", "line5\n","line6\n","writing list of lines"]
 with open("output2.txt", "w") as file:
   file.writelines(lines)


In [98]:
# Method 2: Write a list of lines
lines = ["First line\n", "Second line\n", "Third line\n"]
with open("output1.txt", "w") as file:
 file.writelines(lines)


In [107]:
from datetime import datetime

def log_message(message, level="INFO"):
   """Add a timestamped log entry"""
   timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
   log_entry = f"[{timestamp}] [{level}] {message}\n"
   with open("app.log", "a") as log_file:
     log_file.write(log_entry)
# Usage
log_message("Application started", "INFO")
log_message("User logged in", "INFO")
log_message("Failed to connect to database", "ERROR")

with open("app.log","r") as file:
      print(file.read())

[2026-03-26 08:23:05] [INFO] Application started
[2026-03-26 08:23:05] [INFO] User logged in
[2026-03-26 08:23:05] [ERROR] Failed to connect to database
[2026-03-26 08:23:18] [INFO] Application started
[2026-03-26 08:23:18] [INFO] User logged in
[2026-03-26 08:23:18] [ERROR] Failed to connect to database



In [110]:
def save_user_info():
    name = input("Enter your name: ")
    email = input("Enter your email: ")
    age = input("Enter your age: ")
    with open("users.txt", "a") as file:
      file.write(f"{name},{email},{age}\n")
      print("User information saved!")
save_user_info()


Enter your name: Mini
Enter your email: mini@gmail.com
Enter your age: 23
User information saved!


In [118]:
def add_contact():
   """Add a new contact to the book"""
   name = input("Name: ")
   phone = input("Phone: ")
   email = input("Email: ")
   with open("contacts.txt", "a") as file:
      file.write(f"{name}|{phone}|{email}\n")
      print("Contact added!")
def view_contacts():
    """Display all contacts"""
    try:
      with open("contacts.txt", "r") as file:
          print("\n=== CONTACTS ===")
          for line in file:
              name, phone, email = line.strip().split("|")
              print(f"Name: {name}")
              print(f"Phone: {phone}")
              print(f"Email: {email}")
              print("-" * 30)
    except FileNotFoundError:
       print("No contacts yet!")
# Usage
add_contact()
view_contacts()

Name: mini
Phone: 99898998
Email: kiskkc
Contact added!

=== CONTACTS ===
Name: mini
Phone: 99898998
Email: kiskkc
------------------------------


In [120]:
import json

data = {"name": "John", "age": 25}

with open("data.json", "w") as file:
    print(json.dump(data, file))


None


In [121]:
import os

files = os.listdir(".")
print(files)

['.config', 'output2.txt', 'log_20260326_071915.txt', 'users.txt', 'Test_File.txt', 'contacts.txt', 'data.json', '.ipynb_checkpoints', 'app.log', 'counter.txt', 'text.bin', 'output1.txt', 'log_2026-03-26.txt', 'img24.jpg', 'Test_File1.txt', 'temp.txt', 'Test1_File.txt', 'sample_data']


Create a simple diary app that:
Asks users for a daily entry
Saves it with today's date to diary.txt using append mode
Shows all previous entries when requested


In [125]:
import datetime


todays_date = f"{datetime.date.today()}\n"

with open("diary.txt","a") as file:
  file.write(f"todays date : {todays_date}")
  print("data appended")

data appended


Challenge 2: Write a program that:
Reads a text file
Counts total lines, words, and characters
Displays the statistics (Hint: Use "r" mode and loop through lines

In [126]:
with open("Test_File1.txt","r") as file:
  lines = file.readlines()
  print(f"Total lines: {len(lines)}")

  for line in lines:
    words = line.split()
    print(f"Total words: {len(words)}")

    print(f"Total characters: {len(line)}")

Total lines: 3
Total words: 2
Total characters: 7
Total words: 2
Total characters: 7
Total words: 2
Total characters: 7


Challenge 3: Build a file backup tool that:
Reads a file in binary mode
Creates a copy with .backup extension
Verifies both files are identical (Hint: Use "rb" and "wb" modes)



In [127]:
with open("Test_File.txt","rb") as source:
 data =  source.read()
 with open("test_file.backup", "wb") as destination:
  copied_image = destination.write(data)

Reads current count from counter.txt
Increments it by 1
Writes new count back to the same file (Hint: Use "r+" mode with seek(0) and truncate() )


ValueError: invalid literal for int() with base 10: '43\x00\x00\x00\x00\x00\x00\x00\x0044'

In [ ]:
with open("counter.txt",'r+') as file:
  current = int(file.read())
  print(f"Previous visitors: {current}")

  count = current + 1
  print(f"New visitors: {count}")

  file.seek(0)
  file.write(str(count))
  print("Counter updated")

In [141]:
with open("counter.txt","r+") as file:
   current = int(file.read())
   print(f"Previous visitors: {current}")

   count = current + 1

   file.seek(0)
   file.write(str(count))
   print("Counter updated")


Previous visitors: 43
Counter updated


In [4]:
import numpy as np

numbers = np.arange(10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
numbers.shape = (2, 5)

In [7]:
cube = np.array([[[1, 2], [3, 4]],
[[5, 6], [7, 8]], [[11,12],[13,14]]])
print(cube.shape)

(3, 2, 2)


In [13]:
import numpy as np

arr = np.array([1, 2, 3])
zeros = np.zeros(5)
print(zeros)
sequence = np.arange(0, 10, 2)
print(np.random.randn(2,1))
print(sequence)
print(np.linspace(0, 3, 12))
print(arr.shape)
table = arr.reshape(3, 1)
print(table)

[0. 0. 0. 0. 0.]
[[-1.36541563]
 [-2.28069635]]
[0 2 4 6 8]
[0.         0.27272727 0.54545455 0.81818182 1.09090909 1.36363636
 1.63636364 1.90909091 2.18181818 2.45454545 2.72727273 3.        ]
(3,)
[[1]
 [2]
 [3]]


In [17]:
import numpy as np

num = np.arange(10)
print(num.shape)
print(num.size)
print(num.ndim)

(10,)
10
1


In [19]:
num = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(num.shape)
print(num.reshape(3,4))
print(num.reshape(2,2,3))

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
x = np.arange(20).reshape(4,5)
print(x)

row = x[1:]
column = x[:3]
sub = x[2:, 3:]
va = x[1,2]
print(va)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
7


In [33]:
col = np.arange(4).reshape(4, 1)
row = np.arange(5).reshape(1, 5)
result = col + row
print(result)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [12]:
import pandas as pd
data = {
"Name": ["Alice", "Bob", "Charlie"],
"Age": [28, 35, 22],
"Salary": [55000, 72000, 48000]
}
df = pd.DataFrame(data)



df[["Name","Age"]]

,Name,Age
0,Alice,28
1,Bob,35
2,Charlie,22
