In [3]:
import numpy as np


data_array = np.random.seed(42)
scores = np.random.randint(50,101, size =(5,4))

print(f"Scores : {scores}\n")
print(f"Scores of 3rd student and 2nd subject {scores[2,1]}\n")
print(f"Scores of last 2 students {scores[-2:,:]}\n")
print(f"Scores of first 3 students in subjects 2 and 3: {scores[0:3,1:3]}\n")

average_score = np.round(scores.mean(axis = 0),2)

curve = np.array([5,3,7,2])
curved_scores = scores + curve
curved_scores = np.clip(curved_scores,0,100)

print(f"curved_scores :{curved_scores}")

row_max = curved_scores.max(axis  = 1)
print("Row-wise max:", row_max)

row_min = curved_scores.min(axis=1, keepdims=True)
row_max = curved_scores.max(axis=1, keepdims=True)

normalized = (curved_scores - row_min)/(row_max - row_min)

print("Normalized Scores:\n", normalized)

max_index = np.unravel_index(np.argmax(normalized), normalized.shape)

print("Highest value at (student, subject):", max_index)

high_scores = curved_scores[curved_scores > 90]

print("Scores > 90:", high_scores)



Scores : [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]

Scores of 3rd student and 2nd subject 60

Scores of last 2 students [[85 89 73 52]
 [71 51 73 93]]

Scores of first 3 students in subjects 2 and 3: [[78 64]
 [70 88]
 [60 60]]

curved_scores :[[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]
Row-wise max: [94 95 77 92 95]
Normalized Scores:
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]
Highest value at (student, subject): (np.int64(0), np.int64(3))
Scores > 90: [93 94 95 92 95]


In [4]:
shopping_list = [
    {"item": "Milk", "price": 50},
    {"item": "Bread", "price": 30},
    {"item": "Eggs", "price": 60},
    {"item": "Rice", "price": 120}
]

# Task 1: Add and Remove Items

# Add new item
shopping_list.append({"item": "Butter", "price": 80})

# Remove first item
shopping_list.pop(0)

# Print total items
print(f"Total items: {len(shopping_list)}")
print()

# Task 2: Calculate Total Cost

# Calculate total cost
total_cost = 0
for item in shopping_list:
    total_cost += item["price"]

# Find most expensive item
max_price = 0
expensive_item = ""

for item in shopping_list:
    if item["price"] > max_price:
        max_price = item["price"]
        expensive_item = item["item"]

print(f"Most expensive: {expensive_item} - Rs. {max_price}")
print(f"Total cost: Rs. {total_cost}")
print()

# Task 3: Create Summary Dictionary

# Calculate average
average_price = round(total_cost / len(shopping_list), 2)

# Create summary dictionary
summary = {
    "total_items": len(shopping_list),
    "total_cost": total_cost,
    "average_price": average_price
}

print(f"Summary: {summary}")


Total items: 4

Most expensive: Rice - Rs. 120
Total cost: Rs. 290

Summary: {'total_items': 4, 'total_cost': 290, 'average_price': 72.5}


In [5]:
# STUDENT GRADE BOOK
# Using Lists, Dictionaries, Tuples, and Sets

# List - student names (ordered, mutable)
students = ["Raj", "Priya", "Amit", "Sneha", "Karan"]

# Tuple - subject names (immutable, won't change)
subjects = ("Math", "Science", "English")

# Dictionary - store marks (key-value pairs for easy access)
marks = {
    "Raj": {"Math": 85, "Science": 78, "English": 90},
    "Priya": {"Math": 92, "Science": 88, "English": 85},
    "Amit": {"Math": 70, "Science": 75, "English": 68},
    "Sneha": {"Math": 95, "Science": 90, "English": 92},
    "Karan": {"Math": 80, "Science": 82, "English": 78}
}

# Set - unique grades (no duplicates)
grades = set()

# Display all students
print(f"All Students: {students}")

# Slicing - first 3 students
print(f"First 3 Students: {students[0:3]}\n")

# Calculate averages and assign grades
top_student = ""
highest_avg = 0

for student in students:
    # Get total marks
    total = marks[student]["Math"] + marks[student]["Science"] + marks[student]["English"]

    # Calculate average
    average = total / 3

    # Assign grade
    if average >= 85:
        grade = "A"
    elif average >= 70:
        grade = "B"
    else:
        grade = "C"

    # Add to set
    grades.add(grade)

    # Print student info
    print(f"{student} - Average: {average:.2f} - Grade: {grade}")

    # Track top student
    if average > highest_avg:
        highest_avg = average
        top_student = student

# Display results
print(f"\nTop Student: {top_student}")
print(f"Unique Grades: {grades}")


All Students: ['Raj', 'Priya', 'Amit', 'Sneha', 'Karan']
First 3 Students: ['Raj', 'Priya', 'Amit']

Raj - Average: 84.33 - Grade: B
Priya - Average: 88.33 - Grade: A
Amit - Average: 71.00 - Grade: B
Sneha - Average: 92.33 - Grade: A
Karan - Average: 80.00 - Grade: B

Top Student: Sneha
Unique Grades: {'B', 'A'}


In [6]:
import pandas as pd

# Load dataset
url = "https://drive.google.com/uc?export=download&id=1Mlu9r3afSGz5_02Y3wDJoQLpXszQXaIU"
df = pd.read_csv(url, index_col='order_id')

# Task 1
print("First 5 rows:\n", df.head())
print("\nLast 5 rows:\n", df.tail())

# Task 2
print("\nShape of dataset:", df.shape)
print("\nInfo:")
df.info()

print("\nMissing values:\n", df.isnull().sum())

# Task 3
print("\nStatistical Summary:\n", df.describe())

median_price = df['unit_price'].median()
print("\nMedian unit_price:", median_price)

First 5 rows:
           customer_name   product  quantity  unit_price  order_date     status
order_id                                                                      
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

Last 5 rows:
          customer_name   product  quantity  unit_price  order_date     status
order_id                                                                     
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Key

In [8]:
# Step 1: Initialize variables
total_seats = 350
remaining_seats = 350
total_bookings = 0
tickets_sold = 0
rejected_bookings = 0

# Step 2: Start main booking loop
while True:
    tickets = int(input("Enter number of tickets (0 to exit): "))

    # Step 3: Exit condition
    if tickets == 0:
        break

    # Step 4: Validate ticket count
    if tickets < 1 or tickets > 15:
        print("Invalid number of tickets. Must be between 1 and 15.")
        continue  # skip this iteration

    # Step 5: Check seat availability
    if tickets > remaining_seats:
        print("BOOKING REJECTED - Not enough seats")
        rejected_bookings += 1
        continue

    # Step 6: Collect ages
    ages = []
    for i in range(tickets):
        age = int(input(f"Enter age of person {i+1}: "))
        ages.append(age)

    # Step 7: Validate age restriction
    invalid_age = False
    for age in ages:
        if age < 12:
            invalid_age = True
            break

    # Step 8: Reject if any age < 12
    if invalid_age:
        print("BOOKING REJECTED - Age restriction")
        rejected_bookings += 1
        continue

    # Step 9: Confirm booking
    print(f"BOOKING CONFIRMED - {tickets} tickets")

    total_bookings += 1
    tickets_sold += tickets
    remaining_seats -= tickets

    # Step 10: Stop if theatre is full
    if remaining_seats == 0:
        print("Theatre is now full!")
        break

# Step 11: Final Report
print("\nFINAL REPORT")
print("Total Bookings:", total_bookings)
print("Total Tickets Sold:", tickets_sold)
print("Rejected Bookings:", rejected_bookings)
print("Remaining Seats:", remaining_seats)

Enter number of tickets (0 to exit): 2
Enter age of person 1: 1
Enter age of person 2: 2
BOOKING REJECTED - Age restriction
Enter number of tickets (0 to exit): 0

FINAL REPORT
Total Bookings: 0
Total Tickets Sold: 0
Rejected Bookings: 1
Remaining Seats: 350
